// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: protobuf/message.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OuterFrame struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Nonce            uint64                 `protobuf:"varint,1,opt,name=nonce"`
	xxx_hidden_EncryptedPayload []byte                 `protobuf:"bytes,2,opt,name=encrypted_payload,json=encryptedPayload"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *OuterFrame) Reset() {
	*x = OuterFrame{}
	mi := &file_protobuf_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OuterFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OuterFrame) ProtoMessage() {}

func (x *OuterFrame) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OuterFrame) GetNonce() uint64 {
	if x != nil {
		return x.xxx_hidden_Nonce
	}
	return 0
}

func (x *OuterFrame) GetEncryptedPayload() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedPayload
	}
	return nil
}

func (x *OuterFrame) SetNonce(v uint64) {
	x.xxx_hidden_Nonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *OuterFrame) SetEncryptedPayload(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedPayload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *OuterFrame) HasNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OuterFrame) HasEncryptedPayload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OuterFrame) ClearNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Nonce = 0
}

func (x *OuterFrame) ClearEncryptedPayload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_EncryptedPayload = nil
}

type OuterFrame_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Nonce            *uint64
	EncryptedPayload []byte
}

func (b0 OuterFrame_builder) Build() *OuterFrame {
	m0 := &OuterFrame{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Nonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Nonce = *b.Nonce
	}
	if b.EncryptedPayload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_EncryptedPayload = b.EncryptedPayload
	}
	return m0
}

type InnerMessage struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,1,opt,name=data"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InnerMessage) Reset() {
	*x = InnerMessage{}
	mi := &file_protobuf_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerMessage) ProtoMessage() {}

func (x *InnerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InnerMessage) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *InnerMessage) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *InnerMessage) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *InnerMessage) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Data = nil
}

type InnerMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data []byte
}

func (b0 InnerMessage_builder) Build() *InnerMessage {
	m0 := &InnerMessage{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Data = b.Data
	}
	return m0
}

var File_protobuf_message_proto protoreflect.FileDescriptor

const file_protobuf_message_proto_rawDesc = "" +
	"\n" +
	"\x16protobuf/message.proto\x12\bprotobuf\x1a!google/protobuf/go_features.proto\"O\n" +
	"\n" +
	"OuterFrame\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\x12+\n" +
	"\x11encrypted_payload\x18\x02 \x01(\fR\x10encryptedPayload\"\"\n" +
	"\fInnerMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04dataB\x15Z\v./;protobuf\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_protobuf_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_message_proto_goTypes = []any{
	(*OuterFrame)(nil),   // 0: protobuf.OuterFrame
	(*InnerMessage)(nil), // 1: protobuf.InnerMessage
}
var file_protobuf_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_message_proto_init() }
func file_protobuf_message_proto_init() {
	if File_protobuf_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_message_proto_rawDesc), len(file_protobuf_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_message_proto_goTypes,
		DependencyIndexes: file_protobuf_message_proto_depIdxs,
		MessageInfos:      file_protobuf_message_proto_msgTypes,
	}.Build()
	File_protobuf_message_proto = out.File
	file_protobuf_message_proto_goTypes = nil
	file_protobuf_message_proto_depIdxs = nil
}
