// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Payload

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OuterFrame struct {
	_tab flatbuffers.Table
}

func GetRootAsOuterFrame(buf []byte, offset flatbuffers.UOffsetT) *OuterFrame {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OuterFrame{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *OuterFrame) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OuterFrame) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OuterFrame) Nonce() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OuterFrame) MutateNonce(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *OuterFrame) EncryptedPayload(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *OuterFrame) EncryptedPayloadLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *OuterFrame) EncryptedPayloadBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *OuterFrame) MutateEncryptedPayload(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func OuterFrameStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func OuterFrameAddNonce(builder *flatbuffers.Builder, nonce uint64) {
	builder.PrependUint64Slot(0, nonce, 0)
}
func OuterFrameAddEncryptedPayload(builder *flatbuffers.Builder, encryptedPayload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(encryptedPayload), 0)
}
func OuterFrameStartEncryptedPayloadVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func OuterFrameEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
